# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y6ad-XhyxG-yp6lR5CmBDRg8IW-ziH2r
"""

li = []
li

li = list()
li

str = "khushal"
li = list(str)
li

dir(list)

li = [10]
li

li.append(20)
li

li.insert(3,30)
li

li.insert(5,60)
li

li.append(49)
li

li.clear()
li

del(li)
li

li = [1,2,3,4,5]
li1 = li.copy()
li1

id(li)
id(li1)

id(li[0])

id(li1[0])

li.remove(3)
li

li.count(0)

li + l1

li1 = li.copy()

li + li1

li.extend(li1)
li

li.extend([2,3,4,3,4,3,4,343,34333])
li

li.sort()
li

li

sorted(li)
li